import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import AppChrome from '@/components/layout/AppChrome'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='zh-TW'>
      <head>
        <link rel='preconnect' href='https://picsum.photos' />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-white text-zinc-900 antialiased`}>
        <AppChrome>{children}</AppChrome>
      </body>
    </html>
  )
}
